データベースについて記述、不明点を最後に記述
e195408/java-semi pull request #2
Opened 2021-05-20 19:14 UTC by e195408

# 概要
データベースについて

# 変更内容
主にデータベースに関する表について記述した。

# 補足
その他疑問に思ったこと、質問したいことを忘れないうちに一番下に記述しました。

2021-05-21 04:28 UTC, a171413 commented on README.md
> +### 1. ログイン機能
新規登録機能がない

2021-05-21 04:28 UTC, a171413 commented on README.md
> +### 1. ログイン機能
いきなりログインはおかしい気がする
まずは新規登録機能から

2021-05-21 04:29 UTC, a171413 commented on README.md
>  #### 1. 新規作成機能
新規作成だけだと何を新規作成するのか不明瞭

2021-05-21 04:32 UTC, a171413 commented on README.md
>  #### 2. ログイン機能
大きさが違うのはわかるけど
2. ログイン機能
2. ユーザー機能
となっていると親子関係がわかりにくい。誤記と思われる

2021-05-21 04:35 UTC, a171413 commented on README.md
> +|id|ID|varchar(20)|not null<br>unique|
自動的に付与されたものがidではない？
かならずnumberというものを作る必要がないように思う

2021-05-21 04:35 UTC, a171413 commented on README.md
> +|number|自動的に付与|int|auto_increment<br>primary key|
同上

2021-05-21 04:36 UTC, a171413 commented on README.md
> +|number|自動的に付与|int|auto_increment<br>primary key|
同上

2021-05-21 04:48 UTC, a171413 commented on README.md
> +|store_id|店舗ID|int|not null|
外部キーは各テーブルの一番下に書く

2021-05-21 04:52 UTC, a171413 commented on README.md
>  トップページの店舗一覧画面に登録されている店舗が表示される。
トップページの店舗一覧画面ってどっち？
トップに店舗一覧画面が表示されているということ？

2021-05-21 04:53 UTC, a171413 commented on README.md
> +1.ユーザー
せっかくならここは
#### 3.1 Userテーブル
とかにしたら良いのでは？

2021-05-21 04:54 UTC, a171413 commented on README.md
> +|number|自動的に付与|int|auto_increment<br>primary key|
「自動的に付与」という説明は制約のauto_incrementで十分
なんのために使用するものなのかが説明

2021-05-21 04:55 UTC, a171413 commented on README.md
> +|number|自動的に付与|int|auto_increment<br>primary key|
同上

2021-05-21 04:56 UTC, a171413 commented on README.md
> +|review_id|レビューID|int|not null|
これもreviewテーブルにidがないのに外部キーとして設定することはできない
reviewテーブルにidを作ろう

2021-05-21 04:57 UTC, a171413 commented on README.md
> +店舗詳細の変更はできるか<br>
SQLのupdateコマンドで可能
ただし、変更できないようにすることも可能（ちょっと工夫すれば良い）

2021-05-21 04:58 UTC, a171413 commented on README.md
> +ユーザー詳細のデータベース作成？<br>
これはUserテーブルで良いと思う

2021-05-21 05:03 UTC, a171413 commented on README.md
>  #### 5.フォロー機能
これを作るにはUserテーブルとUserテーブルの中間テーブルが必要そう
例えば
|名前|説明|制約|備考|
|:—-:| :—-: | :—-: | :—-: |
|id|カラム特定のためのID|auto_increment, not null, unique|ユーザーは意識しない|
|follow_user_id|フォローする側のユーザーID|not null|外部キー|
|follower_user_id|フォローされる側のユーザーID|not null|外部キー |

2021-05-21 05:06 UTC, a171413 reviewed
全体的に説明不足感がある
また、1.1や1.1.1という表現をしていないので読む人に親切でない
オブジェクト間に多対多の関係が発生するとき（ex. フォローなど）は中間テーブルを作成すること

2021-05-22 07:33 UTC, a171413 commented on README.md
>  検索を押すと、検索結果画面に遷移する。
入力項目がない

2021-05-22 07:36 UTC, a171413 commented on README.md
> +|name|ユーザーのID|not null<br>unique|
ユーザーのIDがあるんだったらカラム特定のためのIDは不要かも

2021-05-22 07:36 UTC, a171413 commented on README.md
> +|details|店舗詳細|-|
店舗詳細の制約はなし？

2021-05-22 07:36 UTC, a171413 commented on README.md
> +|comment|コメント|-|-
制約はなし？

2021-05-22 07:37 UTC, a171413 commented on README.md
> +|comment|リプライ|not null|-
制約はなし？

2021-05-22 07:38 UTC, a171413 reviewed
おおよそコメント通り
あと，コメントについて認識をすり合わせておきたい
レビューに対して行うのがコメント
コメントに対してコメントというのは考えないということであってる？

2021-05-22 10:27 UTC, e195408 commented on README.md
> +|name|ユーザーのID|not null<br>unique|
ユーザーIDは利用者が任意に決められる、メールアドレスのようなもので、カラム特定のIDは何番目にその人が登録したのか検索できるようなもの(通し番号のようなもの)として用意したのですが通し番号はいらないですか？

2021-05-22 10:29 UTC, e195408 commented on README.md
> +|details|店舗詳細|-|
店舗詳細が空白でも店舗名のみわかっていれば新規店舗の登録ができるようにしたいです。そしてのちに店舗詳細のみ他の人が編集できるようにしたいのですが可能ですか？

2021-05-22 10:32 UTC, e195408 commented on README.md
>  検索を押すと、検索結果画面に遷移する。
日曜日ご教授願います

2021-05-22 10:50 UTC, e195408 commented on README.md
> +|comment|リプライ|not null|-
not nullが制約です

2021-05-22 10:51 UTC, e195408 commented on README.md
> +|comment|コメント|-|-
コメントの制約は無しで、評価だけでもレビューできるようにしたいです

2021-05-22 11:16 UTC, a171413 commented on README.md
>  検索を押すと、検索結果画面に遷移する。
入力項目にユーザーIDがあった方がよくない？ということ
nullで検索されても困るじゃん？

2021-05-22 12:29 UTC, e195408 commented on README.md
>  検索を押すと、検索結果画面に遷移する。
検索の仕様がわからないから触れてないのですが「入力項目、制約、備考」を作った方がわかりやすいってことですか？

2021-05-28 03:34 UTC, a171413 commented on README.md
> +|秘密の質問|全角200文字以内|null不可|
ここも入力させる？
これはあらかじめ用意してある質問から選ばせた方がいい気がする

2021-05-28 03:35 UTC, a171413 commented on README.md
> +|update_at|更新日時|not null|
updated_atにしましょう
更新日時はデフォルトでは入らないんだからnull許容してもいい気がする

2021-05-28 03:36 UTC, a171413 commented on README.md
> +|created_at|作成日時|not null|-
ここに関しては作成日時なくてもいいかも
あったらいい機能があればあってもいいかも

2021-05-28 03:36 UTC, a171413 requested changes
おおよそいい感じです
あとは細かいところっすね

2021-05-28 04:18 UTC, merged