画面遷移に関しての変更
e195408/java-semi pull request #4
Opened 2021-06-03 15:32 UTC by e195408

# 概要
画面遷移について

# 変更内容
マイページとレビューの画面遷移について

2021-06-06 15:50 UTC, a171413 requested changes

2021-06-06 15:50 UTC, a171413 commented on README.md
>  また、アカウントが削除されると、そのユーザーがいままで行った行動(店舗登録やレビュー、フォロー)なども関連して削除される。
今更なんだけど
行動が削除されるんじゃなくて，登録されたレコードが削除されるんだよね？

2021-06-09 11:54 UTC, e195408 commented on README.md
>  また、アカウントが削除されると、そのユーザーがいままで行った行動(店舗登録やレビュー、フォロー)なども関連して削除される。
たしかに，行動の履歴ではなく，ユーザーが登録したレコードが削除されます．書き直した方がいいですか？

2021-06-09 12:30 UTC, a171413 commented on README.md
>  また、アカウントが削除されると、そのユーザーがいままで行った行動(店舗登録やレビュー、フォロー)なども関連して削除される。
そうだね。書き直してadd, commit, pushおなしゃす

2021-06-12 11:47 UTC, a171413 approved these changes

2021-06-12 11:48 UTC, merged